# BLAS ASSIGNMENT

Use the cell below for all your imports.

In [23]:
import numpy as np
from scipy.linalg.blas import dgemv ,ddot, dnrm2,dsymv,

ImportError: cannot import name 'dgetrf' from 'scipy.linalg.blas' (/home/nika/.local/lib/python3.10/site-packages/scipy/linalg/blas.py)

Create a matrix and a vector using NumPy.Their dtype should be double.

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
x = np.array([1, 2, 3], dtype=np.double)

Use BLAS functions to perform matrix-vector multiplication

In [9]:
y = np.zeros_like(x)
alpha = 1.0
beta = 0.0
dgemv(alpha, A, x, beta, y)
print(y)

[0. 0. 0.]


Create two new vectors and calculate their dot product using BLAS functions.

In [12]:
a = np.array([1, 2, 3], dtype=np.double)
b = np.array([4, 5, 6], dtype=np.double)
result = ddot(a, b)
print(result)

32.0


Compute the L2 norm (Euclidean distance) of a vector using BLAS functions

In [16]:
a = np.array([1, 2, 3], dtype=np.double)
norm = dnrm2(a)
print(norm)

3.7416573867739413


Create a 5x5 symmetric matrix and calculate its eigenvalues and eigenvectors using BLAS functions

In [20]:
A = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]], dtype=np.double)
#w, v = dsymv(A)
w,v= np.linalg.eig(A)
print("Eigenvalues:\n", w)
print("Eigenvectors:\n", v)

Eigenvalues:
 [11.34481428 -0.51572947  0.17091519]
Eigenvectors:
 [[-0.32798528 -0.73697623  0.59100905]
 [-0.59100905 -0.32798528 -0.73697623]
 [-0.73697623  0.59100905  0.32798528]]


In [19]:
A = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]], dtype=np.double)
w, v = dsymv(A)
#w,v= np.linalg.eig(A)
print("Eigenvalues:\n", w)
print("Eigenvectors:\n", v)

TypeError: _fblas.dsymv() missing required argument 'x' (pos 3)

Given the following matrix `A` and vector `v`: 

In [24]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
b = np.array([1, 2, 3], dtype=np.double)

Solve the system `Ax = b` using the LU decomposition method and BLAS functions

In [25]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
b = np.array([1, 2, 3], dtype=np.double)
lu, piv = dgetrf(A)
x = blas.dgetri(lu, piv, b)
print(x)

NameError: name 'dgetrf' is not defined

In [26]:
import numpy as np
from scipy.linalg import blas

# Create a matrix
A = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0],
              [7.0, 8.0, 9.0]])

# Compute the LU factorization of A
lu, piv = blas.dgetrf(A)

# Print the result
print("LU factorization of A:\n", lu)
print("Pivot vector:\n", piv)


AttributeError: module 'scipy.linalg.blas' has no attribute 'dgetrf'